server:
  port: 9494

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liumapp/configuration-files
          search-paths: demo

